src/DinnerWebApp/Controllers/DinnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using DinnerWebApp.Data;
using DinnerWebApp.Data.Models;
using DinnerWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DinnerWebApp.Controllers
{
    public class DinnerController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IDataRepository _repository;

        public DinnerController(IMapper mapper, IDataRepository repository)
        {
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        }

        public async Task<ActionResult> Index(int skip = 0, int take = 50)
        {
            var dinners = new List<Dinner>();
            var dinnersFromDatabase = await _repository.GetDinners(skip, take);
            if (dinnersFromDatabase != null && dinnersFromDatabase.Any())
            {
                dinnersFromDatabase.ForEach(e => dinners.Add(_mapper.Map<Dinner>(e)));
            }

            var dinnerModel = new DinnerModel()
            {
                Dinners = dinners,
                Take = take,
                Skip = skip
            };

            var owners = await GetOwners(string.Empty);
            
            var dict = new Dictionary<string, Owner>();

            foreach(var owner in owners)
            {
                dict.Add(owner.Id, owner);
            }

            ViewBag.OwnerList = dict;

            return View(dinnerModel);
        }

        public async Task<ActionResult> AddNewDinner()
        {
            var model = new AddDinnerModel()
            {
                Owners = new List<Owner>(),
                Dinner = new Dinner()
            };

            var owners = await GetOwners(string.Empty);
            ViewBag.OwnerList = ToSelectList(owners, string.Empty, string.Empty);

            return View("AddDinner", model);
        }

        [HttpPost]
        public async Task<ActionResult> Create(Dinner dinner)
        {
            if (dinner != null)
            {
                var dinners = await _repository.Search(dinner.Date);
                if (dinners == null)
                {
                    await _repository.Add(_mapper.Map<DinnerDao>(dinner));
                }
                else
                {
                    // Failed to add dinner.
                    return View("AddDinner", new Dinner());
                }
            }

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Details(DateTime date)
        {
            var dinner = (await _repository.Search(date)).FirstOrDefault();
            var owner = await _repository.GetOwners(dinner.Owner);
            ViewBag.OwnerName = owner.FirstOrDefault().Name;

            return View("Details", _mapper.Map<Dinner>(dinner));
        }

        public async Task<ActionResult> Delete(DateTime date)
        {
            await _repository.DeleteDinner(date);

            return RedirectToAction("Index");
        }

        [NonAction]
        public SelectList ToSelectList(List<Owner> owners, string valueField, string textField)
        {
            List<SelectListItem> list = new List<SelectListItem>();

            foreach (var owner in owners)
            {
                list.Add(new SelectListItem()
                {
                    Text = owner.Name,
                    Value = owner.Id
                });
            }

            return new SelectList(list, "Value", "Text");
        }

        private async Task<List<Owner>> GetOwners(string id)
        {
            var ownerResult = new List<Owner>();
            var ownersFromDatabase = await _repository.GetOwners(id);
            ownersFromDatabase.ForEach(e => ownerResult.Add(_mapper.Map<Owner>(e)));

            return ownerResult;
        }
    }
}

src/DinnerWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dinner" asp-action="Index">Dinner</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-action="Statistics">Statistics</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ellen
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/../Scripts/DatePicker.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>